{{- if .Values.platform.enabled -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.platform.name }}
  labels:
    app: {{ .Values.platform.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.platform.name }}
  strategy: 
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.platform.name }}
    spec:
      serviceAccount: {{ .Values.platform.serviceAccountName }}
      volumes:
      - name: platform-data
      {{- if .Values.platform.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.platform.persistence.existingClaim | default (printf "%s-platform" (include "fullname" .)) | quote }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: helm-access-key
        secret:
          secretName: {{ .Values.global.helmAccessKeyPrivate }}
          defaultMode: 384
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag }}"
        imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.platform.port }}
          protocol: TCP
        livenessProbe:
{{ toYaml .Values.platform.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.platform.readinessProbe | indent 10 }}
        {{- if semverCompare ">=1.19-0" $kubeVersion }}
        startupProbe:
{{ toYaml .Values.platform.startupProbe | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: platform-data
          mountPath: /nmaas/files
          subPath: platform-logs
        - name: platform-data
          mountPath: /home/nmaas/.config/helm
          subPath: helm
        env:
          - name: ENVIRONMENT
            value: "{{ .Values.platform.properties.environment }}"
          {{- if .Values.postgresql.install }}
          - name: POSTGRESQL_HOST
            value: {{ .Release.Name }}-postgresql-hl
          - name: POSTGRESQL_DBNAME
            value: {{ .Values.postgresql.auth.database }}
          - name: POSTGRESQL_USERNAME
            value: {{ .Values.postgresql.auth.username }}
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.postgresql.auth.password }}
          - name: POSTGRESQL_PORT
            value: "5432"
          {{- else }}
          - name: POSTGRESQL_HOST
            value: {{ .Values.platform.properties.postgresql.hostname }}
          - name: POSTGRESQL_DBNAME
            value: {{ .Values.platform.properties.postgresql.database }}
          - name: POSTGRESQL_USERNAME
            value: {{ .Values.platform.properties.postgresql.username }}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.properties.postgresql.password.secret.name }}
                key: {{ .Values.platform.properties.postgresql.password.secret.key }}
          - name: POSTGRESQL_PORT
            value: {{ .Values.platform.properties.postgresql.port | quote }}
          {{- end }}
          - name: ADMIN_EMAIL
            value: {{ .Values.platform.properties.adminEmail }}
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.adminPassword.secret.name }}
                key: {{ .Values.platform.adminPassword.secret.key }}
          - name: PLATFORM_BASEURL
          {{- if .Values.global.demoDeployment }}
            value: "http://{{ .Values.platform.name }}:{{ .Values.platform.port }}"
          {{- else if .Values.platform.tls }}
            value: {{ (printf "https://%s" (.Values.platform.host | default .Values.global.nmaasDomain)) | quote }}
          {{- else }}
            value: {{ (printf "http://%s" (.Values.platform.host | default .Values.global.nmaasDomain)) | quote }}
          {{- end }}
          - name: PLATFORM_PORT
            value: "{{ .Values.platform.port }}"
          - name: PORTAL_HOST
          {{- if .Values.portal.tls }}
            value: {{ (printf "https://%s" (.Values.global.portalHost | default .Values.global.nmaasDomain)) | quote }}
          {{- else }}
            value: {{ (printf "http://%s" (.Values.global.portalHost | default .Values.global.nmaasDomain)) | quote }}
          {{- end }}
          - name: DEPLOYMENT_CHECK_INTERVAL
            value: {{ .Values.platform.properties.serviceDeploymentCheckInterval | quote }}
          - name: DEPLOYMENT_CHECK_TIMEOUT
            value: {{ .Values.platform.properties.serviceDeploymentCheckTimeout | quote }}
          - name: JANITOR_ADDRESS
            value: {{ .Values.platform.properties.janitorHost | default .Values.janitor.name }}
          - name: JANITOR_PORT
            value: {{ .Values.platform.properties.janitorPort | default .Values.janitor.targetPort | quote }}
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.apiSecret.secret.name }}
                key: {{ .Values.platform.apiSecret.secret.key }}
          - name: SMTP_LOGIN
            value: {{ .Values.platform.properties.smtp.login }}
          - name: SMTP_PASSWORD
            value: {{ .Values.platform.properties.smtp.password }}
          - name: SMTP_HOST
            value: {{ .Values.platform.properties.smtp.host | default .Values.postfix.name }}
          - name: SMTP_PORT
            value: {{ .Values.platform.properties.smtp.port | default .Values.postfix.port | quote }}
          {{- if .Values.platform.properties.smtp.from }}
          - name: SMTP_FROM
            value: {{ .Values.platform.properties.smtp.from | quote }}
          {{- end }}
          - name: SMTP_FROM_DEFAULT_DOMAIN
            value: {{ .Values.platform.properties.smtp.defaultDomain | quote }}
          - name: USE_LOGIN_PASSWORD
            value: {{ and .Values.platform.properties.smtp.login .Values.platform.properties.smtp.password }}
          - name: USE_STARTTLS
            value: {{ .Values.platform.properties.smtp.useStartTLS | default "false" | quote }}
          - name: HELM_REPOSITORY
            value: "{{ .Values.platform.properties.helm.repositoryName }}"
          - name: HELM_REPOSITORY_URL
            value: "{{ .Values.platform.properties.helm.repositoryUrl }}"
          - name: HELM_UPDATE_ASYNC_ENABLED 
            value: "{{ .Values.platform.properties.helm.asyncUpdateEnabled }}"
          - name: HELM_UPDATE_ASYNC_CRON
            value: "{{ .Values.platform.properties.helm.asyncUpdateCron }}"
          {{- if not .Values.global.demoDeployment }}
          - name: CAPTCHA_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.properties.captchaSecret.secret.name }}
                key: {{ .Values.platform.properties.captchaSecret.secret.key }}
          {{- end }}
          - name: METRICS_ENABLED
            value: {{ .Values.platform.properties.nmaasMetricsEnabled | default "false" | quote }}
          - name: GITLAB_API_URL
            value: {{ .Values.global.gitlabApiUrl | default "http://nmaas-gitlab-unicorn:8181/api/v4" }}
          - name: GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.gitlabApiToken.secret.name }}
                key: {{ .Values.global.gitlabApiToken.secret.key }}
          - name: K8S_INGRESS_CONTROLLER_INGRESS_CLASS
            value: {{ .Values.platform.properties.k8s.ingress.controller.ingressClass }}
          - name: K8S_INGRESS_CONTROLLER_PUBLIC_INGRESS_CLASS
            value: {{ .Values.platform.properties.k8s.ingress.controller.publicIngressClass }}
          - name: K8S_INGRESS_CONTROLLER_EXTERNAL_SERVICE_DOMAIN
            value: {{ .Values.platform.properties.k8s.ingress.controller.externalServiceDomain }}
          - name: K8S_INGRESS_CONTROLLER_PUBLIC_SERVICE_DOMAIN
            value: {{ .Values.platform.properties.k8s.ingress.controller.publicServiceDomain }}
          - name: K8S_INGRESS_CONTROLLER_TLS_SUPPORTED
            value: {{ .Values.platform.properties.k8s.ingress.controller.tlsSupported | quote }}
          - name: K8S_INGRESS_CONTROLLER_PER_DOMAIN
            value: {{ .Values.platform.properties.k8s.ingress.controller.perDomain | quote }}
          - name: K8S_INGRESS_CERTIFICATE_CONFIG_OPTION
            value: {{ .Values.platform.properties.k8s.ingress.certificate.configOption }}
          - name: K8S_INGRESS_CERTIFICATE_ISSUER_OR_WILDCARD_NAME
            value: {{ .Values.platform.properties.k8s.ingress.certificate.issuerOrWildcardName }}
          - name: K8S_DEPLOYMENT_NAMESPACE_CONFIG_OPTION
            value: {{ .Values.platform.properties.k8s.deployment.namespaceConfigOption }}
          - name: K8S_DEPLOYMENT_DEFAULT_NAMESPACE
            value: {{ .Values.platform.properties.k8s.deployment.defaultNamespace }}
          - name: K8S_DEPLOYMENT_DEFAULT_STORAGE_CLASS
            value: {{ .Values.platform.properties.k8s.deployment.defaultStorageClass }}
          - name: PORTAL_MAINTENANCE_FLAG
            value: {{ .Values.platform.properties.maintenance | quote }}
          - name: PORTAL_TEST_INSTANCE_FLAG
            value: {{ .Values.platform.properties.testInstance | quote }}
          - name: PORTAL_SEND_FAILURE_NOTIF_FLAG
            value: {{ .Values.platform.properties.sendAppInstanceFailureEmails | quote }}
          - name: PORTAL_DEFAULT_LANG
            value: {{ .Values.platform.properties.defaultLanguage }}
          - name: APP_UPGRADE_CRON
            value: {{ .Values.platform.properties.serviceUpgradeCron | quote }}
          - name: APP_UPGRADE_SUMMARY_CRON
            value: {{ .Values.platform.properties.serviceUpgradeSummaryCron | quote }}
          - name: APP_UPGRADE_SUMMARY_INTERVAL
            value: {{ .Values.platform.properties.serviceUpgradeInterval | quote }}
          - name: PLATFORM_API_DOCS_ENABLED
            value: {{ .Values.platform.properties.apiDocsEnabled | quote }}
          - name: PORTAL_DOMAIN_REGISTRATION_SELECTOR
            value: {{ .Values.platform.properties.showDomainRegistrationSelector | quote }}
          - name: NAMESPACE_CREATION_ENABLED
            value: {{ .Values.platform.properties.autoNamespaceCreationForDomains | quote }}
          - name: PORTAL_SSO_ALLOWED_FLAG
            value: {{ .Values.platform.properties.oidc.enabled | quote }}
          {{- if .Values.platform.properties.oidc.enabled }}
          - name: OIDC_CLIENT_ID
            value: {{ .Values.platform.properties.oidc.clientId | quote }}
          - name: OIDC_ISSUER_URI
            value: {{ .Values.platform.properties.oidc.issuerUri | quote }}
          - name: MULTI_INSTANCE_DEPLOYMENT
            value: {{ .Values.platform.properties.multiInstanceSupport | quote }}
          - name: OIDC_USER_LINKING
            value: {{ .Values.platform.properties.oidcUserLinking | quote }}
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.properties.oidc.secretName }}
                key: {{ .Values.platform.properties.oidc.clientSecret.secret.key }}
          {{- end }}
          - name: JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.properties.jwt.secretName }}
                key: {{ .Values.platform.properties.jwt.signingKey.secret.key }}
          - name: JWT_RESET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.properties.jwt.secretName }}
                key: {{ .Values.platform.properties.jwt.resetKey.secret.key }}
      imagePullSecrets:
      - name: {{ .Values.global.registrysecret }}
{{- end -}}
