apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.janitor.clusterRoleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.janitor.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole 
  name: {{ .Values.janitor.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io