{{- if .Values.global.gitlabApiToken.literal }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.global.gitlabApiToken.secret.name | quote }}
data:
  {{ .Values.global.gitlabApiToken.secret.key | quote }}: {{ .Values.global.gitlabApiToken.literal | b64enc | quote }}
{{- end }}