{{- if and .Values.platform.properties.oidc.enabled .Values.platform.properties.oidc.clientSecret.literal }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.platform.properties.oidc.secretName | quote }}
data:
  {{ .Values.platform.properties.oidc.clientSecret.secret.key | quote }}: {{ .Values.platform.properties.oidc.clientSecret.literal | b64enc | quote }}
{{- end }}