apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.platform.clusterRoleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.platform.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.platform.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io

