apiVersion: v2
name: nmaas
description: GÉANT Network Management as a Service Helm chart for Kubernetes
version: 2.0.2-alpha.5
appVersion: latest
keywords:
  - Network Management
  - Cloud Deployment
  - Automated Configuration
maintainers:
  - email: nmaas-admin@lists.geant.org
    name: nmaas-platform
    url: https://docs.nmaas.eu
dependencies:
  - name: postgresql
    version: 16.6.0
    repository: https://artifactory.software.geant.org/artifactory/nmaas-helm-mirror
    condition: postgresql.install
